name: 'degen-tips-readme-action'
description: 'GH Action to automatically add DEGEN tippers from farcaster to your readme'
author: 'dawsbot'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'tophat'
  color: 'black'

# Define your inputs here.
inputs:
  farcaster_username:
    description: 'Farcaster username'
    required: true
  neynar_api_key:
    description: 'Neynar API key'
    required: true
  dune_api_key:
    description: 'Dune API key'
    required: true
  file:
    description: 'File you want to place generated html into'
    required: true
    default: 'README.md'

runs:
  using: node20
  main: dist/index.js
